### ISSUE TITLE
add disclaimer to readme about scan time

### ISSUE THREAD

**Issue by orcutt989** [Lexiebean/CensusPlusTurtle#2]
Could you add a note about how long it might take to scan to the readme? Thanks!

**Comment by Lexiebean** [comment]
I feel like this is too dynamic of a question to be able to answer.

Server population size and any kind of server side rate limiting will impact how long a scan takes.

**Comment by orcutt989** [comment]
How long does it currently take to scan turtle wow?

**Comment by orcutt989** [comment]
Looks like 30m-40m at this time.
