### ISSUE TITLE
Using latest HEAD on branch main - still no data on human hunter/troll warlock

### ISSUE THREAD

**Issue by ahungry** [Lexiebean/CensusPlusTurtle#3]
Are these filters working?  I saw some commits referencing them, but I still can't find either race/class combo (although I didn't check if twow actually lets me make either - but I thought I saw it in the last patch note).

**Comment by ahungry** [comment]
Ah yea, can't make them yet, that's why :laughing:

**Comment by Lexiebean** [comment]
Hehe yeah, they still haven't been released yet. I've just added support for them early.
